This is fixes for the GPU ARM template.
likamrat/foldingathome pull request #38
Opened 2020-05-14 12:39 UTC by chmitch

The Nvidia drivers weren't installed on the prior checkin.  This update switches the template VM to the DSVM image which is preconfigured for all the different classes of GPU VMs.

2020-05-14 14:36 UTC, likamrat commented on deploy/azure/azuredeploy_gpu.json
> +            "fileUris": ["https://raw.githubusercontent.com/chmitch/foldingathome/master/deploy/azure/install_fah_gpu.sh"],
Make sure it's pointing to the right repo

2020-05-14 15:57 UTC, chmitch commented
Updating this PR.   Fixed the errant file path to point to the right repo.   I also fixed the shell script to install nvidia drivers and reverted back to the base ubuntu image.

2020-05-15 01:56 UTC, likamrat commented on docs/AzureGPU.md
> +The ARM Template leverages a parameters file with preconfigured values for things like username and password.   While you can clone this repo and make the necessary modifications to the files to over
Extra space after the first sentence

2020-05-15 02:01 UTC, likamrat commented on docs/AzureGPU.md
>  ![](../img/Azure/az_02.png)
Fix the "Reboot & Shutdown" section at the end of the doc. Currently, it is aligned with Windows.

2020-05-15 02:01 UTC, likamrat requested changes
Fix "Reboot & Shutdown" section

2020-05-19 14:11 UTC, likamrat approved these changes
LGTM

2020-05-19 14:11 UTC, merged